---
title: "House Keeping Genes Plots"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r, echo=F}
library(dplyr)
master_df <- readRDS('K:/Documents/TCGA/Data/normal_data.rds')

```

```{r, eval=FALSE, echo=FALSE }

#plot_ly(master_df, x = ~ACTB, y = ~interaction(gender,IDH)) %>%
#  add_boxplot(color = ~gender) %>%
#  layout(yaxis = list(title = " "))
```
```{r, eval=FALSE, echo=FALSE }
p <- plot_ly(master_df, y = ~raw.pair.count, color = I("steelblue"),
             alpha = 0.1, boxpoints = "suspectedoutliers")
p1 <- p %>% add_boxplot(x='ALB')
p2 <- p %>% add_boxplot(x='B2M')
subplot(
  p1,p2,shareY = TRUE,
  widths = c(0.2, 0.8), margin =0)
```
## Plots {.tabset}
### Count plot by Gender
```{r}
library(RColorBrewer)
pa <- palette(brewer.pal(n=1, name='Pastel2'))
par(mfrow = c(1,3))
    invisible(lapply(50:52, function(i)
      boxplot(master_df[,i]~master_df$gender,
              main= names(master_df[i]),
              xlab='',ylab='Count',
              col=c(pa)
             # bg='white'
      )
    )
    )
```

### Count of HK genes by Race
```{r}
par(mfrow = c(1,3))
invisible(lapply(50:52, function(i)
  boxplot(master_df[,i]~master_df$race,
          main= names(master_df[i]),
          xlab='',ylab='Count',
          col=c(pa)
          # bg='white'
  )
)
)
```

### Count plot by IDH group
```{r}
par(mfrow = c(1,3))
invisible(lapply(50:52, function(i)
boxplot(master_df[,i]~master_df$IDH,
main= names(master_df[i]),
xlab='',ylab='Count',
col=c(pa)
# bg='white'
)
)
)
```

### Count plot by MGMT status 
```{r}
par(mfrow = c(1,3))
invisible(lapply(50:52, function(i)
  boxplot(master_df[,i]~master_df$MGMT,
          main= names(master_df[i]),
          xlab='',ylab='Count',
          col=c(pa)
          # bg='white'
  )
)
)
```

### Count plot by WHO groups 
```{r}
par(mfrow = c(1,3))
invisible(lapply(50:52, function(i)
  boxplot(master_df[,i]~master_df$WHO_groups,
          main= names(master_df[i]),
          xlab='',ylab='Count',
          col=c(pa)
          # bg='white'
  )
)
)
```

### Count plot by Age 
```{r}
plot(master_df$Age, master_df$ACTB, col="#FBB4AE")
points(master_df$Age, master_df$ALB, col="#B3CDE3", pch=19)
points(master_df$Age, master_df$B2M, col="#CCEBC5", pch=19)
legend(2,legend=c('ACTB','ALB','B2M'),
       fill=c("#FBB4AE","#B3CDE3","#CCEBC5"))
```